api_platform:
# The title of the API.
    title: 'API BileMo'
# The description of the API.   
    description: 'The BileMo company provides access to its catalog of high-end mobile phones to all platforms via its API.'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        # To enable or disable eager loading.
        enabled: false

    defaults:
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']